// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDcUVx7V7iuF_lMYLbk2xcAADCuoeTGwk',
    appId: '1:162856044840:web:d1717b19c30cee81db681d',
    messagingSenderId: '162856044840',
    projectId: 'login-page-e19c7',
    authDomain: 'login-page-e19c7.firebaseapp.com',
    storageBucket: 'login-page-e19c7.firebasestorage.app',
    measurementId: 'G-XD7Q44CJDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF1y5IMTvV7IQyTQtkZNMEL197L2KWFng',
    appId: '1:162856044840:android:33685ef940ed8785db681d',
    messagingSenderId: '162856044840',
    projectId: 'login-page-e19c7',
    storageBucket: 'login-page-e19c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Zgc5ag67iGeYt5lRbjV9PJLdZpdY7o4',
    appId: '1:162856044840:ios:41182466042daa1bdb681d',
    messagingSenderId: '162856044840',
    projectId: 'login-page-e19c7',
    storageBucket: 'login-page-e19c7.firebasestorage.app',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Zgc5ag67iGeYt5lRbjV9PJLdZpdY7o4',
    appId: '1:162856044840:ios:41182466042daa1bdb681d',
    messagingSenderId: '162856044840',
    projectId: 'login-page-e19c7',
    storageBucket: 'login-page-e19c7.firebasestorage.app',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDcUVx7V7iuF_lMYLbk2xcAADCuoeTGwk',
    appId: '1:162856044840:web:feebf53ff653c6b4db681d',
    messagingSenderId: '162856044840',
    projectId: 'login-page-e19c7',
    authDomain: 'login-page-e19c7.firebaseapp.com',
    storageBucket: 'login-page-e19c7.firebasestorage.app',
    measurementId: 'G-C6ZQQKW9WQ',
  );
}
